### ISSUE TITLE
Issue in Step 3

### ISSUE THREAD

**Issue by philouc** [zaccharieramzi/git-tuto#3]
To me, there is one missing parameter in Step3. We should write something like
git remote add <name> <URL>
e.g.:
git remote add git-tuto-zacch https://github.com/zaccharieramzi/git-tuto.git

**Comment by zaccharieramzi** [comment]
You are totally right, the change is currently being made by @Gdaval here: https://github.com/zaccharieramzi/git-tuto/pull/2#discussion_r352585985.

**Comment by zaccharieramzi** [comment]
Solved by #2
